language: android

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.2
    - android-26

script:
  - ./gradlew clean testDebug

notifications:
  email: false
  
